// src/views/Beautifier.vue
<template>
  <main class="container">
    <section class="section">
      <h2>Editor</h2>
      <button @click="runBeautifier">Run</button>
      <button @click="clearEditor">Clear</button>
      <select id="inputType" @change="selectInputType">
        <option selected value="json">JSON</option>
        <option value="yaml">YAML</option>
      </select>
      <textarea v-model="editor" name="editor" cols="60" rows="38" />
    </section>
    <section class="section">
      <h2>Output</h2>
      <div ref="output" class="output"></div>
    </section>
  </main>
</template>

<style scoped>
.container {
  display: flex;
  justify-content: center;
}
.section {
  width: 50%;
  padding: 0.5rem;
}
textarea {
  resize: none;
  width: 100%;
}
.output {
  width: 100%;
  background: white;
  height: 86%;
  outline: auto;
  max-height: 77vh;
  overflow-y: auto;
}
</style>

<script lang="ts">
import { defineComponent, ref } from "vue";
import YAML from "yaml";

export default defineComponent({
  name: "Beautifier",
  setup() {
    const editor = ref("");
    const output = ref();
    let selectedOption: string = "json";

    const selectInputType = (e: Event) => {
      const target = <HTMLSelectElement>e.target;
      selectedOption = target.value;
    };

    const clearEditor = () => {
      editor.value = "";
    };

    const getStrAsInputType = () => {
      switch (selectedOption) {
        case "yaml": {
          const inputAsYaml = YAML.parse(editor.value);
          return YAML.stringify(inputAsYaml);
        }
        default: {
          const inputAsJson = JSON.parse(editor.value);
          return JSON.stringify(inputAsJson, undefined, 2);
        }
      }
    };

    const runBeautifier = () => {
      try {
        (<HTMLDivElement>output.value).innerHTML = "";
        const preEl = document.createElement("pre");
        preEl.innerHTML = getStrAsInputType();
        (<HTMLDivElement>output.value).appendChild(preEl);
      } catch (error) {
        (<HTMLDivElement>output.value).innerHTML = error.message;
      }
    };

    return {
      editor,
      output,
      selectInputType,
      clearEditor,
      runBeautifier,
    };
  },
});
</script>

// src/routes/Beautifier/index.tsx
import { h, FunctionalComponent, JSX } from 'preact';
import { useRef } from 'preact/hooks';
import YAML from 'yaml';
import style from './style.css';

const Beautifier: FunctionalComponent = () => {
    const editor = useRef<HTMLTextAreaElement>();
    const output = useRef<HTMLDivElement>();
    const inputType = useRef<HTMLSelectElement>();

    const clearEditor = (): void => {
        editor.current.value = "";
    }

    const getStrAsFormat = (): string => {
        switch (inputType.current.value) {
            case 'yaml': {
                const inputAsYaml = YAML.parse(editor.current.value);
                return YAML.stringify(inputAsYaml);
            }
            default: {
                const inputAsJson = JSON.parse(editor.current.value);
                return JSON.stringify(inputAsJson, undefined, 2);
            }
        }
    }

    const runBeautifier = (): void => {
        try {
            output.current.innerHTML = "";
            const preEl = document.createElement('pre');
            preEl.innerHTML = getStrAsFormat();
            output.current.appendChild(preEl);
        } catch (error) {
            output.current.innerHTML = error.message;
        }
    }

    const selectInputType = (e: JSX.TargetedEvent<HTMLSelectElement>): void => {
        inputType.current.value = e.currentTarget.value;
    }

    return (
        <main class={style.container}>
            <section class={style.section}>
                <h2>Editor</h2>
                <button onClick={runBeautifier}>Run</button>
                <button onClick={clearEditor}>Clear</button>
                <select ref={inputType} name="inputType" id="inputType" onChange={selectInputType}>
                    <option selected value="json">JSON</option>
                    <option value="yaml">YAML</option>
                </select>
                <textarea ref={editor} name="editor" id="editor" cols={60} rows={38} />
            </section>
            <section class={style.section}>
                <h2>Output</h2>
                <div ref={output} class={style.output}>{""}</div>
            </section>
        </main>
    )
}

export default Beautifier;
