// src/routes/Compare/index.tsx
import { FunctionalComponent, h, JSX } from 'preact';
import { useRef } from 'preact/hooks';
import style from './style.css';
import DiffWrapper from './DiffWrapper';

const Compare: FunctionalComponent = () => {
    const editor1 = useRef<HTMLTextAreaElement>();
    const editor2 = useRef<HTMLTextAreaElement>();
    const output = useRef<HTMLPreElement>();
    const inputType = useRef<HTMLSelectElement>();

    const resetFields = (): void => {
        editor1.current.value = "";
        editor2.current.value = "";
        output.current.innerHTML = "";
    }

    const runCompare = (): void => {
        output.current.innerHTML = "";
        let span: HTMLSpanElement, diff: Diff.Change[];
        const fragment = document.createDocumentFragment();
        if (inputType.current.value === 'object') {
            diff = DiffWrapper.diffLines(editor1.current.value, editor2.current.value);
        } else {
            diff = DiffWrapper.diffChars(editor1.current.value, editor2.current.value);
        }
        diff.forEach((part: Record<string, any>) => {
            const color = part.added ? 'green' : part.removed ? 'red' : 'white';
            span = document.createElement('span');
            span.style.background = color;
            span.appendChild(document.createTextNode(part.value));
            fragment.appendChild(span);
        });
        output.current.appendChild(fragment);
    }

    const selectInputType = (e: JSX.TargetedEvent<HTMLSelectElement>): void => {
        inputType.current.value = e.currentTarget.value;
    }

    return (
        <main class={style.container}>
            <section class={style.rows}>
                <div class={style.column}>
                    <h2>Editor 1</h2>
                    <button onClick={runCompare}>Compare</button>
                    <button onClick={resetFields}>Reset</button>
                    <select ref={inputType} name="inputType" id="inputType" onChange={selectInputType}>
                        <option selected value="text">Text</option>
                        <option value="object">Object</option>
                    </select>
                    <textarea ref={editor1} name="editor" id="editor" cols={60} rows={38} />
                </div>
                <div class={style.column}>
                    <h2>Editor 2</h2>
                    <textarea ref={editor2} name="output" id="output" cols={60} rows={38} />
                </div>
            </section>
            <section class={style.rows}>
                <div class={style.column}>
                    <h2>Output</h2>
                    <pre ref={output}>{""}</pre>
                </div>
            </section>
        </main>
    );
};

export default Compare;

// src/views/Compare.vue
<template>
  <main class="container">
    <section class="fields">
      <div class="fields__input">
        <TextArea v-model="compareTo" rows="19" placeholder="Compare to..." />
        <TextArea
          v-model="compareFrom"
          rows="19"
          placeholder="Compare from..."
        />
      </div>
      <div class="fields__btn">
        <Button :onClick="runCompare" title="Compare">
          <img src="@/assets/icon/compare.svg" alt="Compare" />
        </Button>
        <Button :onClick="resetFields" title="Reset">
          <img src="@/assets/icon/reset.svg" alt="Reset" />
        </Button>
        <Dropdown
          :options="['Text', 'Object']"
          :onClick="selectInputType"
          :value="selectedOption"
        />
      </div>
      <div class="fields__output">
        <Clipboard />
        <pre ref="output" class="darkBg" />
      </div>
    </section>
  </main>
</template>

<style scoped>
.container {
  display: flex;
  flex-direction: column;
  justify-content: center;
  align-items: center;
  margin-top: 2rem;
}
.fields {
  display: flex;
  width: 90%;
  min-width: 900px;
}
.fields__input {
  width: 100%;
  height: 100%;
}
.fields__btn {
  margin: 0 2rem;
  height: 200px;
  display: flex;
  flex-direction: column;
}
.fields__btn button {
  padding: 0.4rem;
  width: 100%;
}
.fields__btn img {
  vertical-align: middle;
}
.fields__btn > * {
  margin: 0.5rem 0;
}
.fields__output {
  width: 100%;
  display: flex;
  overflow-y: auto;
  position: relative;
}
.fields__output pre {
  margin: 0;
  width: 100%;
}
</style>

<script lang="ts">
import { defineComponent, ref } from "vue";
import { Button, Dropdown, TextArea, Clipboard } from "@/components/common";

const Diff = require("diff");

export default defineComponent({
  components: {
    Button,
    Dropdown,
    TextArea,
    Clipboard,
  },
  setup() {
    const output = ref();
    const compareTo = ref("");
    const compareFrom = ref("");
    let selectedOption = ref("Text");

    const resetFields = () => {
      (<HTMLDivElement>output.value).innerHTML = "";
      compareTo.value = "";
      compareFrom.value = "";
    };

    const selectInputType = (option: string) => {
      selectedOption.value = option;
    };

    const runCompare = () => {
      (<HTMLDivElement>output.value).innerHTML = "";
      let span: HTMLSpanElement, diff;
      const fragment = document.createDocumentFragment();

      if (selectedOption.value === "Object") {
        diff = Diff.diffLines(compareTo.value, compareFrom.value);
      } else {
        diff = Diff.diffChars(compareTo.value, compareFrom.value);
      }

      diff.forEach((part: Record<string, any>) => {
        const color = part.added
          ? "lightgreen"
          : part.removed
          ? "orange"
          : "white";
        span = document.createElement("span");
        span.style.background = color;
        span.appendChild(document.createTextNode(part.value));
        fragment.appendChild(span);
      });
      (<HTMLDivElement>output.value).appendChild(fragment);
    };

    return {
      output,
      compareTo,
      compareFrom,
      selectInputType,
      resetFields,
      runCompare,
      selectedOption,
    };
  },
});
</script>
